services:
  supabase-db:
    image: supabase/postgres:15.1.0.147  # Updated to a valid tag
    environment:
      - POSTGRES_PASSWORD=5432/postgres
    ports:
      - "5433:5432"
    volumes:
      - supabase_data:/var/lib/postgresql/data
  redis:
    image: redis:latest  # Correct image for Redis
    ports:
      - "6380:6379"
  prometheus:
    image: prom/prometheus  # Correct image for Prometheus
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana  # This seems correct based on pull progress
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
volumes:
  supabase_data:
